export enum State {
	ON = "on",
	OFF = "off",
	HOME = "home",
	NOT_HOME = "not_home",
	UNKNOWN = "unknown",
	OPEN = "open",
	OPENING = "opening",
	CLOSED = "closed",
	CLOSING = "closing",
	BUFFERING = "buffering",
	PLAYING = "playing",
	PAUSED = "paused",
	IDLE = "idle",
	STANDBY = "standby",
	UNAVAILABLE = "unavailable",
	OK = "ok",
	PROBLEM = "problem",
}
